<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251128000936 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dose_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(50) NOT NULL, schedule_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_435930A0A40BC2D5 ON dose_event (schedule_id)');
        $this->addSql('CREATE TABLE medication (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, active_ingredient VARCHAR(255) DEFAULT NULL, form VARCHAR(100) DEFAULT NULL, strength VARCHAR(50) DEFAULT NULL, barcode VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE prescription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dose VARCHAR(100) NOT NULL, frequency VARCHAR(100) NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, patient_id INT NOT NULL, medication_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FBFB8D96B899279 ON prescription (patient_id)');
        $this->addSql('CREATE INDEX IDX_1FBFB8D92C4DE6DA ON prescription (medication_id)');
        $this->addSql('CREATE TABLE schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, time TIME(0) WITHOUT TIME ZONE NOT NULL, days VARCHAR(100) DEFAULT NULL, prescription_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A3811FB93DB413D ON schedule (prescription_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE dose_event ADD CONSTRAINT FK_435930A0A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES schedule (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D96B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D92C4DE6DA FOREIGN KEY (medication_id) REFERENCES medication (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB93DB413D FOREIGN KEY (prescription_id) REFERENCES prescription (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dose_event DROP CONSTRAINT FK_435930A0A40BC2D5');
        $this->addSql('ALTER TABLE prescription DROP CONSTRAINT FK_1FBFB8D96B899279');
        $this->addSql('ALTER TABLE prescription DROP CONSTRAINT FK_1FBFB8D92C4DE6DA');
        $this->addSql('ALTER TABLE schedule DROP CONSTRAINT FK_5A3811FB93DB413D');
        $this->addSql('DROP TABLE dose_event');
        $this->addSql('DROP TABLE medication');
        $this->addSql('DROP TABLE prescription');
        $this->addSql('DROP TABLE schedule');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
